### ISSUE TITLE
数据问题请教

### ISSUE THREAD

**Issue by HappyCoderGS** [AlexYangLi/ccks2019_el#5]
您好，请教下数据问题，ccks2019_el文件中有develop.json，kb_data，train.json三个文件，请问测试集是哪个呢？另一个问题就是B榜的测试集指的是复赛的测试集吗？

**Comment by AlexYangLi** [comment]
你好，develop.json是A榜（初赛）的测试集。B榜的测试集就是复赛的测试集。
