### ISSUE TITLE
Would you please explain a few about how you generate candidate for ambiguous entity ?

### ISSUE THREAD

**Issue by CoinCheung** [AlexYangLi/ccks2019_el#9]
Hi, 

You mentioned briefly in README that how you choose the correct entity from the candidates, would you please explain a bit about how did you generate the candidates ?

**Comment by AlexYangLi** [comment]
Hi, in the provided knowledge base, each entity has a "subject" field and a "alias" field, which records the surface forms of corresponding entity. And we call them "mentions". Base on that, we can build a map from mention to entities to generate candidate entities.

**Comment by CoinCheung** [comment]
Could I understand that the candidates are just predefined in the knowledge graph, and we just need to look at each entity to see the potential matches and use them as candidates?

**Comment by AlexYangLi** [comment]
yes

**Comment by CoinCheung** [comment]
Thanks for replying !!! 

By the way, what is the cuda/cudnn version you have on you platform. I run into some cudnn errors like this: 
```
tensorflow.python.framework.errors_impl.UnknownError: Fail to find the dnn implementation.
	 [[Node: bidirectional_1/CudnnRNN = CudnnRNN[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/bidirectional_1/CudnnRNN_grad/CudnnRNNBackprop"], direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bidirectional_1/transpose, bidirectional_1/ExpandDims_1, bidirectional_1/ExpandDims_1, bidirectional_1/concat)]]

```

**Comment by AlexYangLi** [comment]
This code was run on tf1.8, with cuda 9.1 and cudnn 7.1

**Comment by CoinCheung** [comment]
It works, thanks a lot!!! I am closing this.
